packages:
  - apps/*
  - servers/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - better-sqlite3
  - canvas
  - esbuild
  - prisma
  - sharp
  - simple-git-hooks
  - vue-demi
  - vue3-sketch-ruler
