export const fontFamily = [
  { label: "Serif-字体", value: "sans-serif" },
  { label: "Arial-字体", value: "Arial" },
  { label: "思源黑体-Normal", value: "siayuan-normal" },
  { label: "思源黑体-Regular", value: "siayuan-regular" },
  { label: "思源黑体-Bold", value: "siayuan-bold" },
  { label: "DIN-粗体", value: "DIN-Bold" },
  { label: "DIN-黑体", value: "DIN-Black" },
  { label: "DIN-黑斜体", value: "DIN-BlackItalic" },
  { label: "DIN-粗斜体", value: "DIN-BoldItalic" },
  { label: "DINCond-粗体", value: "DINCond-Bold" },
  { label: "DINCond-细体", value: "DINCond-Light" },
  { label: "DINCond-中等体", value: "DIN-Bold-Medium" },
  { label: "DIN-细体", value: "DIN-Light" },
  { label: "DIN-细斜体", value: "DIN-LightItalic" },
  { label: "DIN-中等斜体", value: "DIN-MediumItalic" },
  { label: "DIN-常规体", value: "DIN-Regular" },
  { label: "DIN-常规斜体", value: "DIN-RegularItalic" },
  { label: "D-DIN-压缩体", value: "D-DINCondensed" },
  { label: "D-DIN-压缩粗体", value: "D-DINCondensed-Bold" },
  { label: "OPPO Sans字体", value: "OppOOPPOSans" },
  { label: "庞门正道标题体", value: "PangMenZhengDaoBiaoTiTi-1" },
  { label: "庞门正道粗书体", value: "PangMenZhengDaoCuShuTi-2" },
  { label: "阿里巴巴普惠体", value: "Alibaba-PuHuiTi-Regular" },
  { label: "造字工房悦黑", value: "造字工房悦黑" },
  { label: "优设标题黑", value: "优设标题黑" }
];
