/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_alignmentresult_free: (a: number, b: number) => void;
export const __wbg_horizontalline_free: (a: number, b: number) => void;
export const __wbg_verticalline_free: (a: number, b: number) => void;
export const alignmentresult_new: (a: number, b: number) => number;
export const alignmentresult_offset_x: (a: number) => number;
export const alignmentresult_offset_y: (a: number) => number;
export const alignmentresult_zero: () => number;
export const horizontalline_xs: (a: number) => [number, number];
export const horizontalline_y: (a: number) => number;
export const verticalline_x: (a: number) => number;
export const verticalline_ys: (a: number) => [number, number];
export const __wbg_bialignmentinstance_free: (a: number, b: number) => void;
export const __wbg_binode_free: (a: number, b: number) => void;
export const bialignmentinstance_add_node: (a: number, b: number) => number;
export const bialignmentinstance_cache_reference_shapes: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const bialignmentinstance_clear_alignment: (a: number) => void;
export const bialignmentinstance_delete_node: (a: number, b: number) => number;
export const bialignmentinstance_get_horizontal_lines: (a: number) => [number, number];
export const bialignmentinstance_get_vertical_lines: (a: number) => [number, number];
export const bialignmentinstance_initialize: (a: number, b: number, c: number) => void;
export const bialignmentinstance_new: (a: number) => number;
export const bialignmentinstance_search_point: (a: number, b: number, c: number) => [number, number];
export const bialignmentinstance_update_node: (a: number, b: number, c: number) => number;
export const bialignmentinstance_update_ref_line: (a: number, b: number, c: number, d: number, e: number) => number;
export const binode_height: (a: number) => number;
export const binode_id: (a: number) => number;
export const binode_left: (a: number) => number;
export const binode_new: (a: number, b: number, c: number, d: number, e: number) => number;
export const binode_top: (a: number) => number;
export const binode_width: (a: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_alloc: () => number;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
