// 环境变量
const { MINIO_BASE_URL } = process.env;
const { WEB_APP_MINIO_BASE_URL } = (window as any).webconfig;
export const ftPeriodictableConfig = {
  jsonData: {
    sceneVersionId: 4,
    keyframeAnimation: [],
    coordinateOptions: {
      lat: 39.89945,
      lon: 116.40969,
      scale: 12,
      opacity: 0.6,
      rotation: 0,
      mapZoom: 12
    },
    statesAnimation: [],
    baseUrl: WEB_APP_MINIO_BASE_URL || MINIO_BASE_URL,
    curScene: {
      name: "状态1",
      environment: {
        lightIconVisible: true,
        skyBox: {
          skyType: "sphere",
          type: "noBackGround",
          imageType: "default",
          envMapType: "customize",
          texture: "version-test/assets/scene/skyBox/lightsky.jpg",
          image: "",
          video: "",
          position: [0, 0, 0],
          rotateY: 0,
          radius: 6000,
          distance: 10000,
          cloudSpeed: 0.02,
          cloudScale: 2.1,
          cloudInt: 0.5,
          skycolor1: "#336699",
          skycolor2: "#66b2ff",
          color: "rgba(210,210,210,1)",
          envSourceUrl: "version-test/assets/scene/envmap",
          isFollowSkyBox: false,
          environment: "",
          environmentIntensity: 1,
          backgroundRotationY: 0,
          environmentRotationY: 0
        },
        lights: [
          {
            index: "43635eb4-3d1e-4023-8ab3-8a32f6dacdd1",
            tabsName: "灯光1",
            show: false,
            type: "ambientLight",
            intensity: 0.3,
            color: "rgba(255,255,255,1)",
            skyColor: "rgba(255,255,255,1)",
            groundColor: "rgba(255,255,255,1)",
            distance: 500,
            rotateY: -160,
            rotateX: -40,
            angle: 60,
            position: [1000, 1000, 1000],
            shadowArea: 300,
            target: [0, 0, 0],
            isFollowCamera: false,
            isCastShadow: false,
            bias: -0.001,
            mapSize: "4096,4096",
            radius: 100,
            focus: 1,
            isHelper: true,
            specular: "rgba(255,255,255,1)",
            penumbra: 0.62,
            shadowIntensity: 1,
            width: 1000,
            height: 1000
          }
        ],
        fog: {
          isOpen: false,
          color: "rgba(210,210,210,1)",
          near: 500,
          far: 1500,
          disabledHeight: true,
          fogTop: 3000,
          fogBottom: 0,
          isDefault: true
        },
        skyCloud: {
          isOpen: false,
          type: "sky",
          skyType: "dynamic",
          cloudType: 0,
          cloudy: 0.6,
          speed: 0.001,
          angle: 89,
          enableSunLight: true,
          enableCloud: true,
          time: 17,
          exposure: 0.9,
          height: 1500,
          thickness: 0.23
        },
        renderer: {
          envType: "neutral",
          envHdr: "",
          shadowEnabled: true,
          toneMapping: 1,
          exposure: 1,
          outputEncoding: 3001
        },
        postProcessing: {
          enabled: true,
          ssrEnabled: false,
          ssrOpacity: 0.8,
          ssrDistance: 0,
          ssrThickness: 0,
          gtaoEnabled: false,
          gtaoRadius: 0.5,
          gtaoIntensity: 0.8,
          sharpenEnabled: false,
          sharpness: 0.2,
          dofEnabled: false,
          dofFocus: 50,
          dofAperture: 0.025,
          dofMaxblur: 0.01,
          unrealBloomEnabled: false,
          bloomStrength: 0.6,
          bloomRadius: 0.7,
          bloomThreshold: 0.7,
          globalUnrealBloomEnabled: false,
          globalBloomStrength: 0.3,
          globalBloomRadius: 0.7,
          globalBloomThreshold: 0.7,
          colorCorrectEnabled: false,
          colorExposure: 0.03,
          colorBrightness: -0.6,
          colorContrast: -0.9,
          colorSaturation: 0.3,
          coloTemperature: 0,
          colorTint: 0,
          colorHue: 0,
          lutEnabled: false,
          lutIntensity: 0.2,
          lutType: "Lenox 340",
          lutUrl: "version-test/assets/scene/lut",
          antiAliasingType: "MSAA",
          smaaEnabled: false,
          fxaaEnabled: false,
          msaaEnabled: true,
          samples: 4,
          flowEnabled: false,
          flowIntensity: 1,
          flowColor: "rgba(255,255,255,1)",
          flowPosition: [0, 0, 0],
          flowSpeed: 0.5,
          flowMaxRadius: 5000,
          godRayEnable: false,
          godRayBlurriness: 1,
          godRayDensity: 0.96,
          godRayDecay: 0.98,
          godRayWeight: 0.3,
          godRayExposure: 0.54,
          godRayClampMax: 1,
          godRaySamples: 32,
          godRayColor: "rgba(255,221,170,1)",
          godRayOpacity: 1,
          godRayRadius: 40,
          godRayResolutionScale: 0.5,
          godRayPosition: [1500, 150, 1500],
          outlineEnabled: false,
          gammaEnabled: false
        },
        spaceEffect: [
          {
            show: false,
            type: "",
            tabsName: "特效1",
            index: "O9P8uLG2-8eNL-4511-8LuI-GXVk02mcN1wG"
          }
        ],
        camera: {
          autoRotate: false,
          viewLimitEnable: true,
          fov: 45,
          distanceMin: 1,
          distanceMax: 3000,
          viewDistanceMin: 1,
          viewDistanceMax: 50000,
          inclinationAngleMin: -90,
          inclinationAngleMax: 90,
          rotationAngleLimited: false,
          rotationAngleMin: -180,
          rotationAngleMax: 180,
          positionCenter: [0, 0, 0],
          positionMin: [-1000, -1000, -1000],
          positionMax: [1000, 1000, 1000],
          position: [0, 0, 1500],
          target: [0, 0, 0],
          flyTime: [1.5],
          flyInterval: 0,
          dollySpeed: 0.05,
          truckSpeed: 1,
          polarRotateSpeed: 1,
          azimuthRotateSpeed: 1,
          dampingFactor: 0.5,
          draggingDampingFactor: 0.25
        },
        publishQuality: {
          resolution: "orignal",
          effect: "none",
          shadow: "medium",
          texture: "medium",
          mergeType: "merge",
          num: 10
        },
        performance: {
          type: "none",
          num: 5
        },
        animation: {
          keyframes: [],
          states: []
        }
      },
      models: []
    },
    sceneList: [],
    previewState: true
  }
};
