export const DecorationPreset = {
  line: [
    {
      label: "预设1",
      preview: "version-test/assets/image/flexDecoAssets/preview_line/2.png",
      config: {
        configType: "preset",
        flexType: "horizontal",
        styleIndex: 1,
        opacityGlobal: 0,
        lineBodyPic: "version-test/assets/image/flexDecoAssets/line/2-m.png",
        lineBodyHeight: 5,
        lineBodyDisplay: true,
        lineLeftPic: "version-test/assets/image/flexDecoAssets/line/2-l.png",
        lineLeftWidth: 50,
        lineLeftRight: 45,
        lineLeftOpacity: 0,
        lineLeftDisplay: true,
        lineRightPic: "version-test/assets/image/flexDecoAssets/line/2-r.png",
        lineRightWidth: 50,
        lineRightHeight: 50,
        lineRightOpacity: 0,
        lineRightDisplay: true,
        lineBodyOpacity: 0,
        lineLeftHeight: 50
      }
    },
    {
      label: "预设2",
      preview: "version-test/assets/image/flexDecoAssets/preview_line/6.png",
      config: {
        configType: "preset",
        flexType: "horizontal",
        styleIndex: 1,
        opacityGlobal: 1,
        lineBodyPic: "version-test/assets/image/flexDecoAssets/line/6-m.png",
        lineBodyHeight: 10,
        lineBodyDisplay: true,
        lineLeftPic: "version-test/assets/image/flexDecoAssets/line/6-l.png",
        lineLeftWidth: 45,
        lineLeftRight: 45,
        lineLeftOpacity: 0,
        lineLeftDisplay: true,
        lineRightPic: "version-test/assets/image/flexDecoAssets/line/6-r.png",
        lineRightWidth: 45,
        lineRightHeight: 45,
        lineRightOpacity: 0,
        lineRightDisplay: true,
        lineBodyOpacity: 0
      }
    },
    {
      label: "预设3",
      preview: "version-test/assets/image/flexDecoAssets/preview_line/7.png",
      config: {
        configType: "preset",
        flexType: "horizontal",
        styleIndex: 1,
        opacityGlobal: 1,
        lineBodyPic: "version-test/assets/image/flexDecoAssets/line/7-m.png",
        lineBodyHeight: 30,
        lineBodyDisplay: true,
        lineLeftPic: "version-test/assets/image/flexDecoAssets/line/7-l.png",
        lineLeftWidth: 45,
        lineLeftRight: 45,
        lineLeftOpacity: 0,
        lineLeftDisplay: true,
        lineRightPic: "version-test/assets/image/flexDecoAssets/line/7-r.png",
        lineRightWidth: 45,
        lineRightHeight: 45,
        lineRightOpacity: 0,
        lineRightDisplay: true,
        lineBodyOpacity: 0
      }
    },
    {
      label: "预设4",
      preview: "version-test/assets/image/flexDecoAssets/preview_line/12.png",
      config: {
        configType: "preset",
        flexType: "horizontal",
        styleIndex: 1,
        opacityGlobal: 1,
        lineBodyPic: "version-test/assets/image/flexDecoAssets/line/12-m.png",
        lineBodyHeight: 25,
        lineBodyDisplay: true,
        lineLeftPic: "version-test/assets/image/flexDecoAssets/line/12-l.png",
        lineLeftWidth: 45,
        lineLeftRight: 45,
        lineLeftOpacity: 0,
        lineLeftDisplay: true,
        lineRightPic: "version-test/assets/image/flexDecoAssets/line/12-r.png",
        lineRightWidth: 45,
        lineRightHeight: 45,
        lineRightOpacity: 0,
        lineRightDisplay: true,
        lineBodyOpacity: 0
      }
    },
    {
      label: "预设5",
      preview: "version-test/assets/image/flexDecoAssets/preview_line/13.png",
      config: {
        configType: "preset",
        flexType: "horizontal",
        styleIndex: 1,
        opacityGlobal: 1,
        lineBodyPic: "version-test/assets/image/flexDecoAssets/line/13-m.png",
        lineBodyHeight: 45,
        lineBodyDisplay: true,
        lineLeftPic: "version-test/assets/image/flexDecoAssets/line/13-l.png",
        lineLeftWidth: 45,
        lineLeftRight: 45,
        lineLeftOpacity: 0,
        lineLeftDisplay: true,
        lineRightPic: "version-test/assets/image/flexDecoAssets/line/13-r.png",
        lineRightWidth: 45,
        lineRightHeight: 45,
        lineRightOpacity: 0,
        lineRightDisplay: true,
        lineBodyOpacity: 0
      }
    },
    {
      label: "预设6",
      preview: "version-test/assets/image/flexDecoAssets/preview_line/14.png",
      config: {
        configType: "preset",
        flexType: "horizontal",
        styleIndex: 1,
        opacityGlobal: 1,
        lineBodyPic: "version-test/assets/image/flexDecoAssets/line/14-m.png",
        lineBodyHeight: 45,
        lineBodyDisplay: true,
        lineLeftPic: "version-test/assets/image/flexDecoAssets/line/14-l.png",
        lineLeftWidth: 45,
        lineLeftRight: 45,
        lineLeftOpacity: 0,
        lineLeftDisplay: true,
        lineRightPic: "version-test/assets/image/flexDecoAssets/line/14-r.png",
        lineRightWidth: 45,
        lineRightHeight: 45,
        lineRightOpacity: 0,
        lineRightDisplay: true,
        lineBodyOpacity: 0
      }
    },
    {
      label: "预设7",
      preview: "version-test/assets/image/flexDecoAssets/preview_line/15.png",
      config: {
        configType: "preset",
        flexType: "horizontal",
        styleIndex: 1,
        opacityGlobal: 1,
        lineBodyPic: "version-test/assets/image/flexDecoAssets/line/15-m.png",
        lineBodyHeight: 45,
        lineBodyDisplay: true,
        lineLeftPic: "version-test/assets/image/flexDecoAssets/line/15-l.png",
        lineLeftWidth: 45,
        lineLeftRight: 45,
        lineLeftOpacity: 0,
        lineLeftDisplay: true,
        lineRightPic: "version-test/assets/image/flexDecoAssets/line/15-r.png",
        lineRightWidth: 45,
        lineRightHeight: 45,
        lineRightOpacity: 0,
        lineRightDisplay: true,
        lineBodyOpacity: 0
      }
    },
    {
      label: "预设8",
      preview: "version-test/assets/image/flexDecoAssets/preview_line/16.png",
      config: {
        configType: "preset",
        flexType: "horizontal",
        styleIndex: 1,
        opacityGlobal: 1,
        lineBodyPic: "version-test/assets/image/flexDecoAssets/line/16-m.png",
        lineBodyHeight: 45,
        lineBodyDisplay: true,
        lineLeftPic: "version-test/assets/image/flexDecoAssets/line/16-l.png",
        lineLeftWidth: 45,
        lineLeftRight: 45,
        lineLeftOpacity: 0,
        lineLeftDisplay: true,
        lineRightPic: "version-test/assets/image/flexDecoAssets/line/16-r.png",
        lineRightWidth: 45,
        lineRightHeight: 45,
        lineRightOpacity: 0,
        lineRightDisplay: true,
        lineBodyOpacity: 0
      }
    },
    {
      label: "预设9",
      preview: "version-test/assets/image/flexDecoAssets/preview_line/17.png",
      config: {
        configType: "preset",
        flexType: "horizontal",
        styleIndex: 1,
        opacityGlobal: 1,
        lineBodyPic: "version-test/assets/image/flexDecoAssets/line/17-m.png",
        lineBodyHeight: 45,
        lineBodyDisplay: true,
        lineLeftPic: "version-test/assets/image/flexDecoAssets/line/17-l.png",
        lineLeftWidth: 45,
        lineLeftRight: 45,
        lineLeftOpacity: 0,
        lineLeftDisplay: true,
        lineRightPic: "version-test/assets/image/flexDecoAssets/line/17-r.png",
        lineRightWidth: 45,
        lineRightHeight: 45,
        lineRightOpacity: 0,
        lineRightDisplay: true,
        lineBodyOpacity: 0
      }
    }
  ],
  rect: [
    {
      label: "预设1",
      preview: "version-test/assets/image/flexDecoAssets/preview_rect/1.png",
      config: {
        configType: "preset",
        flexType: "corner",
        styleIndex: 1,
        opacityGlobal: 1,
        cornerTLPic: "version-test/assets/image/flexDecoAssets/rect/1.png",
        cornerTLWidth: 45,
        cornerTLHeight: 45,
        cornerTLOpacity: 1,
        cornerTLDisplay: true,
        cornerTRPic: "version-test/assets/image/flexDecoAssets/rect/1-1.png",
        cornerTRWidth: 45,
        cornerTRHeight: 45,
        cornerTROpacity: 1,
        cornerTRDisplay: true,
        cornerBLPic: "version-test/assets/image/flexDecoAssets/rect/1-2.png",
        cornerBLWidth: 45,
        cornerBLHeight: 45,
        cornerBLOpacity: 1,
        cornerBLDisplay: true,
        cornerBRPic: "version-test/assets/image/flexDecoAssets/rect/1-3.png",
        cornerBRWidth: 45,
        cornerBRHeight: 45,
        cornerBROpacity: 1,
        cornerBRDisplay: 1
      }
    },
    {
      label: "预设2",
      preview: "version-test/assets/image/flexDecoAssets/preview_rect/3.png",
      config: {
        configType: "preset",
        flexType: "corner",
        styleIndex: 1,
        opacityGlobal: 1,
        cornerTLPic: "version-test/assets/image/flexDecoAssets/rect/3.png",
        cornerTLWidth: 45,
        cornerTLHeight: 45,
        cornerTLOpacity: 1,
        cornerTLDisplay: true,
        cornerTRPic: "version-test/assets/image/flexDecoAssets/rect/3-1.png",
        cornerTRWidth: 45,
        cornerTRHeight: 45,
        cornerTROpacity: 1,
        cornerTRDisplay: true,
        cornerBLPic: "version-test/assets/image/flexDecoAssets/rect/3-2.png",
        cornerBLWidth: 45,
        cornerBLHeight: 45,
        cornerBLOpacity: 1,
        cornerBLDisplay: true,
        cornerBRPic: "version-test/assets/image/flexDecoAssets/rect/3-3.png",
        cornerBRWidth: 45,
        cornerBRHeight: 45,
        cornerBROpacity: 1,
        cornerBRDisplay: 1
      }
    },
    {
      label: "预设3",
      preview: "version-test/assets/image/flexDecoAssets/preview_rect/4.png",
      config: {
        configType: "preset",
        flexType: "corner",
        styleIndex: 1,
        opacityGlobal: 1,
        cornerTLPic: "version-test/assets/image/flexDecoAssets/rect/4.png",
        cornerTLWidth: 45,
        cornerTLHeight: 45,
        cornerTLOpacity: 1,
        cornerTLDisplay: true,
        cornerTRPic: "version-test/assets/image/flexDecoAssets/rect/4-1.png",
        cornerTRWidth: 45,
        cornerTRHeight: 45,
        cornerTROpacity: 1,
        cornerTRDisplay: true,
        cornerBLPic: "version-test/assets/image/flexDecoAssets/rect/4-2.png",
        cornerBLWidth: 45,
        cornerBLHeight: 45,
        cornerBLOpacity: 1,
        cornerBLDisplay: true,
        cornerBRPic: "version-test/assets/image/flexDecoAssets/rect/4-3.png",
        cornerBRWidth: 45,
        cornerBRHeight: 45,
        cornerBROpacity: 1,
        cornerBRDisplay: 1
      }
    },
    {
      label: "预设4",
      preview: "version-test/assets/image/flexDecoAssets/preview_rect/5.png",
      config: {
        configType: "preset",
        flexType: "corner",
        styleIndex: 1,
        opacityGlobal: 1,
        cornerTLPic: "version-test/assets/image/flexDecoAssets/rect/5.png",
        cornerTLWidth: 45,
        cornerTLHeight: 45,
        cornerTLOpacity: 1,
        cornerTLDisplay: true,
        cornerTRPic: "version-test/assets/image/flexDecoAssets/rect/5-1.png",
        cornerTRWidth: 45,
        cornerTRHeight: 45,
        cornerTROpacity: 1,
        cornerTRDisplay: true,
        cornerBLPic: "version-test/assets/image/flexDecoAssets/rect/5-2.png",
        cornerBLWidth: 45,
        cornerBLHeight: 45,
        cornerBLOpacity: 1,
        cornerBLDisplay: true,
        cornerBRPic: "version-test/assets/image/flexDecoAssets/rect/5-3.png",
        cornerBRWidth: 45,
        cornerBRHeight: 45,
        cornerBROpacity: 1,
        cornerBRDisplay: 1
      }
    },
    {
      label: "预设5",
      preview: "version-test/assets/image/flexDecoAssets/preview_rect/8.png",
      config: {
        configType: "preset",
        flexType: "corner",
        styleIndex: 1,
        opacityGlobal: 1,
        cornerTLPic: "version-test/assets/image/flexDecoAssets/rect/8.png",
        cornerTLWidth: 45,
        cornerTLHeight: 45,
        cornerTLOpacity: 1,
        cornerTLDisplay: true,
        cornerTRPic: "version-test/assets/image/flexDecoAssets/rect/8-1.png",
        cornerTRWidth: 45,
        cornerTRHeight: 45,
        cornerTROpacity: 1,
        cornerTRDisplay: true,
        cornerBLPic: "version-test/assets/image/flexDecoAssets/rect/8-2.png",
        cornerBLWidth: 45,
        cornerBLHeight: 45,
        cornerBLOpacity: 1,
        cornerBLDisplay: true,
        cornerBRPic: "version-test/assets/image/flexDecoAssets/rect/8-3.png",
        cornerBRWidth: 45,
        cornerBRHeight: 45,
        cornerBROpacity: 1,
        cornerBRDisplay: 1
      }
    },
    {
      label: "预设6",
      preview: "version-test/assets/image/flexDecoAssets/preview_rect/9.png",
      config: {
        configType: "preset",
        flexType: "corner",
        styleIndex: 1,
        opacityGlobal: 1,
        cornerTLPic: "version-test/assets/image/flexDecoAssets/rect/9.png",
        cornerTLWidth: 45,
        cornerTLHeight: 45,
        cornerTLOpacity: 1,
        cornerTLDisplay: true,
        cornerTRPic: "version-test/assets/image/flexDecoAssets/rect/9-1.png",
        cornerTRWidth: 45,
        cornerTRHeight: 45,
        cornerTROpacity: 1,
        cornerTRDisplay: true,
        cornerBLPic: "version-test/assets/image/flexDecoAssets/rect/9-2.png",
        cornerBLWidth: 45,
        cornerBLHeight: 45,
        cornerBLOpacity: 1,
        cornerBLDisplay: true,
        cornerBRPic: "version-test/assets/image/flexDecoAssets/rect/9-3.png",
        cornerBRWidth: 45,
        cornerBRHeight: 45,
        cornerBROpacity: 1,
        cornerBRDisplay: 1
      }
    },
    {
      label: "预设7",
      preview: "version-test/assets/image/flexDecoAssets/preview_rect/10.png",
      config: {
        configType: "preset",
        flexType: "corner",
        styleIndex: 1,
        opacityGlobal: 1,
        cornerTLPic: "version-test/assets/image/flexDecoAssets/rect/10.png",
        cornerTLWidth: 45,
        cornerTLHeight: 45,
        cornerTLOpacity: 1,
        cornerTLDisplay: true,
        cornerTRPic: "version-test/assets/image/flexDecoAssets/rect/10-1.png",
        cornerTRWidth: 45,
        cornerTRHeight: 45,
        cornerTROpacity: 1,
        cornerTRDisplay: true,
        cornerBLPic: "version-test/assets/image/flexDecoAssets/rect/10-2.png",
        cornerBLWidth: 45,
        cornerBLHeight: 45,
        cornerBLOpacity: 1,
        cornerBLDisplay: true,
        cornerBRPic: "version-test/assets/image/flexDecoAssets/rect/10-3.png",
        cornerBRWidth: 45,
        cornerBRHeight: 45,
        cornerBROpacity: 1,
        cornerBRDisplay: 1
      }
    },
    {
      label: "预设8",
      preview: "version-test/assets/image/flexDecoAssets/preview_rect/11.png",
      config: {
        configType: "preset",
        flexType: "corner",
        styleIndex: 1,
        opacityGlobal: 1,
        cornerTLPic: "version-test/assets/image/flexDecoAssets/rect/11.png",
        cornerTLWidth: 45,
        cornerTLHeight: 45,
        cornerTLOpacity: 1,
        cornerTLDisplay: true,
        cornerTRPic: "version-test/assets/image/flexDecoAssets/rect/11-1.png",
        cornerTRWidth: 45,
        cornerTRHeight: 45,
        cornerTROpacity: 1,
        cornerTRDisplay: true,
        cornerBLPic: "version-test/assets/image/flexDecoAssets/rect/11-2.png",
        cornerBLWidth: 45,
        cornerBLHeight: 45,
        cornerBLOpacity: 1,
        cornerBLDisplay: true,
        cornerBRPic: "version-test/assets/image/flexDecoAssets/rect/11-3.png",
        cornerBRWidth: 45,
        cornerBRHeight: 45,
        cornerBROpacity: 1,
        cornerBRDisplay: 1
      }
    }
  ]
};

export const ConfigType = [
  { label: "预设", value: "preset" },
  { label: "自定义", value: "custom" }
];

export const FlexTypes = [
  { label: "左中右", value: "horizontal" },
  { label: "上中下", value: "vertical" },
  { label: "四角布局", value: "corner" }
];
